// Code generated by protoc-gen-go. DO NOT EDIT.
// source: game.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	protobuf "google/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RulesType int32

const (
	RulesType_NONE_MATCH            RulesType = 0
	RulesType_SINGLE_ROW_MATCH      RulesType = 1
	RulesType_SINGLE_COL_MATCH      RulesType = 2
	RulesType_SINGLE_DIAGONAL_MATCH RulesType = 3
	RulesType_TWO_ROWS_MATCH        RulesType = 4
	RulesType_TWO_COLS_MATCH        RulesType = 5
	RulesType_TWO_DIAGONAL_MATCH    RulesType = 6
	RulesType_FULL_HOUSE            RulesType = 7
)

var RulesType_name = map[int32]string{
	0: "NONE_MATCH",
	1: "SINGLE_ROW_MATCH",
	2: "SINGLE_COL_MATCH",
	3: "SINGLE_DIAGONAL_MATCH",
	4: "TWO_ROWS_MATCH",
	5: "TWO_COLS_MATCH",
	6: "TWO_DIAGONAL_MATCH",
	7: "FULL_HOUSE",
}

var RulesType_value = map[string]int32{
	"NONE_MATCH":            0,
	"SINGLE_ROW_MATCH":      1,
	"SINGLE_COL_MATCH":      2,
	"SINGLE_DIAGONAL_MATCH": 3,
	"TWO_ROWS_MATCH":        4,
	"TWO_COLS_MATCH":        5,
	"TWO_DIAGONAL_MATCH":    6,
	"FULL_HOUSE":            7,
}

func (x RulesType) String() string {
	return proto.EnumName(RulesType_name, int32(x))
}

func (RulesType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

type StartSessionRequest struct {
	GameName             string              `protobuf:"bytes,1,opt,name=gameName,proto3" json:"gameName,omitempty"`
	SecretPhrase         string              `protobuf:"bytes,2,opt,name=secretPhrase,proto3" json:"secretPhrase,omitempty"`
	StartedAt            *protobuf.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StartSessionRequest) Reset()         { *m = StartSessionRequest{} }
func (m *StartSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StartSessionRequest) ProtoMessage()    {}
func (*StartSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{0}
}

func (m *StartSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionRequest.Unmarshal(m, b)
}
func (m *StartSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionRequest.Marshal(b, m, deterministic)
}
func (m *StartSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionRequest.Merge(m, src)
}
func (m *StartSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StartSessionRequest.Size(m)
}
func (m *StartSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionRequest proto.InternalMessageInfo

func (m *StartSessionRequest) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *StartSessionRequest) GetSecretPhrase() string {
	if m != nil {
		return m.SecretPhrase
	}
	return ""
}

func (m *StartSessionRequest) GetStartedAt() *protobuf.Timestamp {
	if m != nil {
		return m.StartedAt
	}
	return nil
}

type StartSessionResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	GameLink             string   `protobuf:"bytes,2,opt,name=gameLink,proto3" json:"gameLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StartSessionResponse) Reset()         { *m = StartSessionResponse{} }
func (m *StartSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StartSessionResponse) ProtoMessage()    {}
func (*StartSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{1}
}

func (m *StartSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StartSessionResponse.Unmarshal(m, b)
}
func (m *StartSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StartSessionResponse.Marshal(b, m, deterministic)
}
func (m *StartSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StartSessionResponse.Merge(m, src)
}
func (m *StartSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StartSessionResponse.Size(m)
}
func (m *StartSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StartSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StartSessionResponse proto.InternalMessageInfo

func (m *StartSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *StartSessionResponse) GetGameLink() string {
	if m != nil {
		return m.GameLink
	}
	return ""
}

type GetSessionRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionRequest) Reset()         { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()    {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{2}
}

func (m *GetSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionRequest.Unmarshal(m, b)
}
func (m *GetSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionRequest.Marshal(b, m, deterministic)
}
func (m *GetSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionRequest.Merge(m, src)
}
func (m *GetSessionRequest) XXX_Size() int {
	return xxx_messageInfo_GetSessionRequest.Size(m)
}
func (m *GetSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionRequest proto.InternalMessageInfo

func (m *GetSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	GameLink             string   `protobuf:"bytes,2,opt,name=gameLink,proto3" json:"gameLink,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSessionResponse) Reset()         { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()    {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{3}
}

func (m *GetSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSessionResponse.Unmarshal(m, b)
}
func (m *GetSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSessionResponse.Marshal(b, m, deterministic)
}
func (m *GetSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSessionResponse.Merge(m, src)
}
func (m *GetSessionResponse) XXX_Size() int {
	return xxx_messageInfo_GetSessionResponse.Size(m)
}
func (m *GetSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSessionResponse proto.InternalMessageInfo

func (m *GetSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *GetSessionResponse) GetGameLink() string {
	if m != nil {
		return m.GameLink
	}
	return ""
}

type AddPlayerRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlayerRequest) Reset()         { *m = AddPlayerRequest{} }
func (m *AddPlayerRequest) String() string { return proto.CompactTextString(m) }
func (*AddPlayerRequest) ProtoMessage()    {}
func (*AddPlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{4}
}

func (m *AddPlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerRequest.Unmarshal(m, b)
}
func (m *AddPlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerRequest.Marshal(b, m, deterministic)
}
func (m *AddPlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerRequest.Merge(m, src)
}
func (m *AddPlayerRequest) XXX_Size() int {
	return xxx_messageInfo_AddPlayerRequest.Size(m)
}
func (m *AddPlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerRequest proto.InternalMessageInfo

func (m *AddPlayerRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AddPlayerRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AddPlayerResponse struct {
	SheetSize            int32    `protobuf:"varint,1,opt,name=sheetSize,proto3" json:"sheetSize,omitempty"`
	Sheet                []int32  `protobuf:"varint,2,rep,packed,name=sheet,proto3" json:"sheet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPlayerResponse) Reset()         { *m = AddPlayerResponse{} }
func (m *AddPlayerResponse) String() string { return proto.CompactTextString(m) }
func (*AddPlayerResponse) ProtoMessage()    {}
func (*AddPlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{5}
}

func (m *AddPlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPlayerResponse.Unmarshal(m, b)
}
func (m *AddPlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPlayerResponse.Marshal(b, m, deterministic)
}
func (m *AddPlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPlayerResponse.Merge(m, src)
}
func (m *AddPlayerResponse) XXX_Size() int {
	return xxx_messageInfo_AddPlayerResponse.Size(m)
}
func (m *AddPlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPlayerResponse proto.InternalMessageInfo

func (m *AddPlayerResponse) GetSheetSize() int32 {
	if m != nil {
		return m.SheetSize
	}
	return 0
}

func (m *AddPlayerResponse) GetSheet() []int32 {
	if m != nil {
		return m.Sheet
	}
	return nil
}

type PlayersListRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayersListRequest) Reset()         { *m = PlayersListRequest{} }
func (m *PlayersListRequest) String() string { return proto.CompactTextString(m) }
func (*PlayersListRequest) ProtoMessage()    {}
func (*PlayersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{6}
}

func (m *PlayersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersListRequest.Unmarshal(m, b)
}
func (m *PlayersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersListRequest.Marshal(b, m, deterministic)
}
func (m *PlayersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersListRequest.Merge(m, src)
}
func (m *PlayersListRequest) XXX_Size() int {
	return xxx_messageInfo_PlayersListRequest.Size(m)
}
func (m *PlayersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersListRequest proto.InternalMessageInfo

func (m *PlayersListRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type PlayersListResponse struct {
	Players              []string `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayersListResponse) Reset()         { *m = PlayersListResponse{} }
func (m *PlayersListResponse) String() string { return proto.CompactTextString(m) }
func (*PlayersListResponse) ProtoMessage()    {}
func (*PlayersListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{7}
}

func (m *PlayersListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayersListResponse.Unmarshal(m, b)
}
func (m *PlayersListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayersListResponse.Marshal(b, m, deterministic)
}
func (m *PlayersListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayersListResponse.Merge(m, src)
}
func (m *PlayersListResponse) XXX_Size() int {
	return xxx_messageInfo_PlayersListResponse.Size(m)
}
func (m *PlayersListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayersListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlayersListResponse proto.InternalMessageInfo

func (m *PlayersListResponse) GetPlayers() []string {
	if m != nil {
		return m.Players
	}
	return nil
}

type EnablePlayerRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=playerName,proto3" json:"playerName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnablePlayerRequest) Reset()         { *m = EnablePlayerRequest{} }
func (m *EnablePlayerRequest) String() string { return proto.CompactTextString(m) }
func (*EnablePlayerRequest) ProtoMessage()    {}
func (*EnablePlayerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{8}
}

func (m *EnablePlayerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnablePlayerRequest.Unmarshal(m, b)
}
func (m *EnablePlayerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnablePlayerRequest.Marshal(b, m, deterministic)
}
func (m *EnablePlayerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnablePlayerRequest.Merge(m, src)
}
func (m *EnablePlayerRequest) XXX_Size() int {
	return xxx_messageInfo_EnablePlayerRequest.Size(m)
}
func (m *EnablePlayerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnablePlayerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnablePlayerRequest proto.InternalMessageInfo

func (m *EnablePlayerRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *EnablePlayerRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

type EnablePlayerResponse struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	PlayerEnabled        bool     `protobuf:"varint,2,opt,name=playerEnabled,proto3" json:"playerEnabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnablePlayerResponse) Reset()         { *m = EnablePlayerResponse{} }
func (m *EnablePlayerResponse) String() string { return proto.CompactTextString(m) }
func (*EnablePlayerResponse) ProtoMessage()    {}
func (*EnablePlayerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{9}
}

func (m *EnablePlayerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnablePlayerResponse.Unmarshal(m, b)
}
func (m *EnablePlayerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnablePlayerResponse.Marshal(b, m, deterministic)
}
func (m *EnablePlayerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnablePlayerResponse.Merge(m, src)
}
func (m *EnablePlayerResponse) XXX_Size() int {
	return xxx_messageInfo_EnablePlayerResponse.Size(m)
}
func (m *EnablePlayerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnablePlayerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnablePlayerResponse proto.InternalMessageInfo

func (m *EnablePlayerResponse) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *EnablePlayerResponse) GetPlayerEnabled() bool {
	if m != nil {
		return m.PlayerEnabled
	}
	return false
}

type RulesListRequest struct {
	SessionId            string      `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Rules                []RulesType `protobuf:"varint,2,rep,packed,name=rules,proto3,enum=proto.RulesType" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RulesListRequest) Reset()         { *m = RulesListRequest{} }
func (m *RulesListRequest) String() string { return proto.CompactTextString(m) }
func (*RulesListRequest) ProtoMessage()    {}
func (*RulesListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{10}
}

func (m *RulesListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RulesListRequest.Unmarshal(m, b)
}
func (m *RulesListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RulesListRequest.Marshal(b, m, deterministic)
}
func (m *RulesListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesListRequest.Merge(m, src)
}
func (m *RulesListRequest) XXX_Size() int {
	return xxx_messageInfo_RulesListRequest.Size(m)
}
func (m *RulesListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RulesListRequest proto.InternalMessageInfo

func (m *RulesListRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *RulesListRequest) GetRules() []RulesType {
	if m != nil {
		return m.Rules
	}
	return nil
}

type RulesListResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RulesListResponse) Reset()         { *m = RulesListResponse{} }
func (m *RulesListResponse) String() string { return proto.CompactTextString(m) }
func (*RulesListResponse) ProtoMessage()    {}
func (*RulesListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{11}
}

func (m *RulesListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RulesListResponse.Unmarshal(m, b)
}
func (m *RulesListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RulesListResponse.Marshal(b, m, deterministic)
}
func (m *RulesListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RulesListResponse.Merge(m, src)
}
func (m *RulesListResponse) XXX_Size() int {
	return xxx_messageInfo_RulesListResponse.Size(m)
}
func (m *RulesListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RulesListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RulesListResponse proto.InternalMessageInfo

func (m *RulesListResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type DrawNumberRequest struct {
	SesssionId           string   `protobuf:"bytes,1,opt,name=sesssionId,proto3" json:"sesssionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawNumberRequest) Reset()         { *m = DrawNumberRequest{} }
func (m *DrawNumberRequest) String() string { return proto.CompactTextString(m) }
func (*DrawNumberRequest) ProtoMessage()    {}
func (*DrawNumberRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{12}
}

func (m *DrawNumberRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawNumberRequest.Unmarshal(m, b)
}
func (m *DrawNumberRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawNumberRequest.Marshal(b, m, deterministic)
}
func (m *DrawNumberRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawNumberRequest.Merge(m, src)
}
func (m *DrawNumberRequest) XXX_Size() int {
	return xxx_messageInfo_DrawNumberRequest.Size(m)
}
func (m *DrawNumberRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawNumberRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawNumberRequest proto.InternalMessageInfo

func (m *DrawNumberRequest) GetSesssionId() string {
	if m != nil {
		return m.SesssionId
	}
	return ""
}

type DrawNumberResponse struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawNumberResponse) Reset()         { *m = DrawNumberResponse{} }
func (m *DrawNumberResponse) String() string { return proto.CompactTextString(m) }
func (*DrawNumberResponse) ProtoMessage()    {}
func (*DrawNumberResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{13}
}

func (m *DrawNumberResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawNumberResponse.Unmarshal(m, b)
}
func (m *DrawNumberResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawNumberResponse.Marshal(b, m, deterministic)
}
func (m *DrawNumberResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawNumberResponse.Merge(m, src)
}
func (m *DrawNumberResponse) XXX_Size() int {
	return xxx_messageInfo_DrawNumberResponse.Size(m)
}
func (m *DrawNumberResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawNumberResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrawNumberResponse proto.InternalMessageInfo

func (m *DrawNumberResponse) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

type AttachRequest struct {
	SesssionId           string   `protobuf:"bytes,1,opt,name=sesssionId,proto3" json:"sesssionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachRequest) Reset()         { *m = AttachRequest{} }
func (m *AttachRequest) String() string { return proto.CompactTextString(m) }
func (*AttachRequest) ProtoMessage()    {}
func (*AttachRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{14}
}

func (m *AttachRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachRequest.Unmarshal(m, b)
}
func (m *AttachRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachRequest.Marshal(b, m, deterministic)
}
func (m *AttachRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachRequest.Merge(m, src)
}
func (m *AttachRequest) XXX_Size() int {
	return xxx_messageInfo_AttachRequest.Size(m)
}
func (m *AttachRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachRequest proto.InternalMessageInfo

func (m *AttachRequest) GetSesssionId() string {
	if m != nil {
		return m.SesssionId
	}
	return ""
}

type DrawnNumbersListRequest struct {
	SesssionId           string   `protobuf:"bytes,1,opt,name=sesssionId,proto3" json:"sesssionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawnNumbersListRequest) Reset()         { *m = DrawnNumbersListRequest{} }
func (m *DrawnNumbersListRequest) String() string { return proto.CompactTextString(m) }
func (*DrawnNumbersListRequest) ProtoMessage()    {}
func (*DrawnNumbersListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{15}
}

func (m *DrawnNumbersListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawnNumbersListRequest.Unmarshal(m, b)
}
func (m *DrawnNumbersListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawnNumbersListRequest.Marshal(b, m, deterministic)
}
func (m *DrawnNumbersListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawnNumbersListRequest.Merge(m, src)
}
func (m *DrawnNumbersListRequest) XXX_Size() int {
	return xxx_messageInfo_DrawnNumbersListRequest.Size(m)
}
func (m *DrawnNumbersListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawnNumbersListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DrawnNumbersListRequest proto.InternalMessageInfo

func (m *DrawnNumbersListRequest) GetSesssionId() string {
	if m != nil {
		return m.SesssionId
	}
	return ""
}

type DrawnNumbersResponse struct {
	Numbers              []int32  `protobuf:"varint,1,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DrawnNumbersResponse) Reset()         { *m = DrawnNumbersResponse{} }
func (m *DrawnNumbersResponse) String() string { return proto.CompactTextString(m) }
func (*DrawnNumbersResponse) ProtoMessage()    {}
func (*DrawnNumbersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{16}
}

func (m *DrawnNumbersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DrawnNumbersResponse.Unmarshal(m, b)
}
func (m *DrawnNumbersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DrawnNumbersResponse.Marshal(b, m, deterministic)
}
func (m *DrawnNumbersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DrawnNumbersResponse.Merge(m, src)
}
func (m *DrawnNumbersResponse) XXX_Size() int {
	return xxx_messageInfo_DrawnNumbersResponse.Size(m)
}
func (m *DrawnNumbersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DrawnNumbersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DrawnNumbersResponse proto.InternalMessageInfo

func (m *DrawnNumbersResponse) GetNumbers() []int32 {
	if m != nil {
		return m.Numbers
	}
	return nil
}

type StopSessionRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopSessionRequest) Reset()         { *m = StopSessionRequest{} }
func (m *StopSessionRequest) String() string { return proto.CompactTextString(m) }
func (*StopSessionRequest) ProtoMessage()    {}
func (*StopSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{17}
}

func (m *StopSessionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSessionRequest.Unmarshal(m, b)
}
func (m *StopSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSessionRequest.Marshal(b, m, deterministic)
}
func (m *StopSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSessionRequest.Merge(m, src)
}
func (m *StopSessionRequest) XXX_Size() int {
	return xxx_messageInfo_StopSessionRequest.Size(m)
}
func (m *StopSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopSessionRequest proto.InternalMessageInfo

func (m *StopSessionRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type StopSessionResponse struct {
	SessionId            string              `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Status               bool                `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	StoppedAt            *protobuf.Timestamp `protobuf:"bytes,3,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StopSessionResponse) Reset()         { *m = StopSessionResponse{} }
func (m *StopSessionResponse) String() string { return proto.CompactTextString(m) }
func (*StopSessionResponse) ProtoMessage()    {}
func (*StopSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{18}
}

func (m *StopSessionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopSessionResponse.Unmarshal(m, b)
}
func (m *StopSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopSessionResponse.Marshal(b, m, deterministic)
}
func (m *StopSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopSessionResponse.Merge(m, src)
}
func (m *StopSessionResponse) XXX_Size() int {
	return xxx_messageInfo_StopSessionResponse.Size(m)
}
func (m *StopSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StopSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StopSessionResponse proto.InternalMessageInfo

func (m *StopSessionResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *StopSessionResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *StopSessionResponse) GetStoppedAt() *protobuf.Timestamp {
	if m != nil {
		return m.StoppedAt
	}
	return nil
}

type AnnounceWinnersRequest struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceWinnersRequest) Reset()         { *m = AnnounceWinnersRequest{} }
func (m *AnnounceWinnersRequest) String() string { return proto.CompactTextString(m) }
func (*AnnounceWinnersRequest) ProtoMessage()    {}
func (*AnnounceWinnersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{19}
}

func (m *AnnounceWinnersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceWinnersRequest.Unmarshal(m, b)
}
func (m *AnnounceWinnersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceWinnersRequest.Marshal(b, m, deterministic)
}
func (m *AnnounceWinnersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceWinnersRequest.Merge(m, src)
}
func (m *AnnounceWinnersRequest) XXX_Size() int {
	return xxx_messageInfo_AnnounceWinnersRequest.Size(m)
}
func (m *AnnounceWinnersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceWinnersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceWinnersRequest proto.InternalMessageInfo

func (m *AnnounceWinnersRequest) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

type AnnounceWinnersResponse struct {
	SessionId            string   `protobuf:"bytes,1,opt,name=sessionId,proto3" json:"sessionId,omitempty"`
	Player               string   `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnnounceWinnersResponse) Reset()         { *m = AnnounceWinnersResponse{} }
func (m *AnnounceWinnersResponse) String() string { return proto.CompactTextString(m) }
func (*AnnounceWinnersResponse) ProtoMessage()    {}
func (*AnnounceWinnersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_38fc58335341d769, []int{20}
}

func (m *AnnounceWinnersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnnounceWinnersResponse.Unmarshal(m, b)
}
func (m *AnnounceWinnersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnnounceWinnersResponse.Marshal(b, m, deterministic)
}
func (m *AnnounceWinnersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnnounceWinnersResponse.Merge(m, src)
}
func (m *AnnounceWinnersResponse) XXX_Size() int {
	return xxx_messageInfo_AnnounceWinnersResponse.Size(m)
}
func (m *AnnounceWinnersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AnnounceWinnersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AnnounceWinnersResponse proto.InternalMessageInfo

func (m *AnnounceWinnersResponse) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *AnnounceWinnersResponse) GetPlayer() string {
	if m != nil {
		return m.Player
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.RulesType", RulesType_name, RulesType_value)
	proto.RegisterType((*StartSessionRequest)(nil), "proto.StartSessionRequest")
	proto.RegisterType((*StartSessionResponse)(nil), "proto.StartSessionResponse")
	proto.RegisterType((*GetSessionRequest)(nil), "proto.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "proto.GetSessionResponse")
	proto.RegisterType((*AddPlayerRequest)(nil), "proto.AddPlayerRequest")
	proto.RegisterType((*AddPlayerResponse)(nil), "proto.AddPlayerResponse")
	proto.RegisterType((*PlayersListRequest)(nil), "proto.PlayersListRequest")
	proto.RegisterType((*PlayersListResponse)(nil), "proto.PlayersListResponse")
	proto.RegisterType((*EnablePlayerRequest)(nil), "proto.EnablePlayerRequest")
	proto.RegisterType((*EnablePlayerResponse)(nil), "proto.EnablePlayerResponse")
	proto.RegisterType((*RulesListRequest)(nil), "proto.RulesListRequest")
	proto.RegisterType((*RulesListResponse)(nil), "proto.RulesListResponse")
	proto.RegisterType((*DrawNumberRequest)(nil), "proto.DrawNumberRequest")
	proto.RegisterType((*DrawNumberResponse)(nil), "proto.DrawNumberResponse")
	proto.RegisterType((*AttachRequest)(nil), "proto.AttachRequest")
	proto.RegisterType((*DrawnNumbersListRequest)(nil), "proto.DrawnNumbersListRequest")
	proto.RegisterType((*DrawnNumbersResponse)(nil), "proto.DrawnNumbersResponse")
	proto.RegisterType((*StopSessionRequest)(nil), "proto.StopSessionRequest")
	proto.RegisterType((*StopSessionResponse)(nil), "proto.StopSessionResponse")
	proto.RegisterType((*AnnounceWinnersRequest)(nil), "proto.AnnounceWinnersRequest")
	proto.RegisterType((*AnnounceWinnersResponse)(nil), "proto.AnnounceWinnersResponse")
}

func init() { proto.RegisterFile("game.proto", fileDescriptor_38fc58335341d769) }

var fileDescriptor_38fc58335341d769 = []byte{
	// 849 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xf2, 0x46,
	0x10, 0x8d, 0x21, 0x10, 0x98, 0xfc, 0x14, 0x36, 0x34, 0x71, 0xdc, 0x96, 0xa2, 0x55, 0x55, 0xa1,
	0xb6, 0x82, 0x94, 0x48, 0x95, 0x72, 0x69, 0x01, 0x21, 0x48, 0xd4, 0x4e, 0x6d, 0xa2, 0xf4, 0xa2,
	0x12, 0x32, 0x61, 0x9b, 0xa0, 0x82, 0xed, 0xe2, 0x45, 0x51, 0xfa, 0x00, 0xbd, 0xee, 0x73, 0xf4,
	0xb2, 0x4f, 0x58, 0x79, 0x77, 0x6d, 0xd6, 0xc6, 0x5f, 0x3e, 0xa2, 0xef, 0x0a, 0xe6, 0xcc, 0xce,
	0xf1, 0xd9, 0xf1, 0xcc, 0x31, 0xc0, 0x93, 0xb3, 0x24, 0x2d, 0x7f, 0xe5, 0x51, 0x0f, 0x15, 0xd8,
	0x8f, 0xf6, 0xf5, 0x93, 0xe7, 0x3d, 0x2d, 0x48, 0x9b, 0x45, 0xd3, 0xf5, 0xef, 0x6d, 0x3a, 0x5f,
	0x92, 0x80, 0x3a, 0x4b, 0x9f, 0x9f, 0xc3, 0xff, 0x28, 0x70, 0x6a, 0x53, 0x67, 0x45, 0x6d, 0x12,
	0x04, 0x73, 0xcf, 0xb5, 0xc8, 0x9f, 0x6b, 0x12, 0x50, 0xa4, 0x41, 0x29, 0x64, 0x33, 0x9c, 0x25,
	0x51, 0x95, 0x86, 0xd2, 0x2c, 0x5b, 0x71, 0x8c, 0x30, 0x1c, 0x05, 0xe4, 0x71, 0x45, 0xe8, 0xdd,
	0xf3, 0xca, 0x09, 0x88, 0x9a, 0x63, 0xf9, 0x04, 0x86, 0xae, 0x01, 0x82, 0x90, 0x96, 0xcc, 0x26,
	0x0e, 0x55, 0xf3, 0x0d, 0xa5, 0x79, 0xd8, 0xd1, 0x5a, 0x5c, 0x4d, 0x2b, 0x52, 0xd3, 0x1a, 0x47,
	0x6a, 0xac, 0xb2, 0x38, 0xad, 0x53, 0x7c, 0x07, 0xb5, 0xa4, 0xa2, 0xc0, 0xf7, 0xdc, 0x80, 0xa0,
	0x2f, 0xa1, 0x1c, 0x70, 0x68, 0x38, 0x13, 0x9a, 0x36, 0x40, 0x24, 0x78, 0x34, 0x77, 0xff, 0x10,
	0x82, 0xe2, 0x18, 0xff, 0x08, 0xd5, 0x01, 0x49, 0xdf, 0xf0, 0x4d, 0x3a, 0x6c, 0x00, 0x92, 0x4b,
	0x3e, 0x59, 0x42, 0x0f, 0x2a, 0xfa, 0x6c, 0x76, 0xb7, 0x70, 0x5e, 0xc9, 0x6a, 0x27, 0x05, 0x08,
	0xc1, 0xbe, 0x1b, 0x76, 0x9f, 0x33, 0xb1, 0xff, 0x78, 0x00, 0x55, 0x89, 0x45, 0x12, 0xf5, 0x4c,
	0x08, 0xb5, 0xe7, 0x7f, 0xf1, 0x77, 0x55, 0xb0, 0x36, 0x00, 0xaa, 0x41, 0x81, 0x05, 0x6a, 0xae,
	0x91, 0x6f, 0x16, 0x2c, 0x1e, 0xe0, 0x0e, 0x20, 0xce, 0x12, 0x8c, 0xe6, 0x01, 0xdd, 0xad, 0x25,
	0x6d, 0x38, 0x4d, 0xd4, 0x88, 0xc7, 0xab, 0x70, 0xe0, 0x73, 0x58, 0x55, 0x1a, 0xf9, 0x66, 0xd9,
	0x8a, 0x42, 0x6c, 0xc3, 0x69, 0xdf, 0x75, 0xa6, 0x0b, 0xf2, 0x9e, 0x6b, 0xd7, 0x01, 0x78, 0xbd,
	0xb1, 0xb9, 0xbc, 0x84, 0xe0, 0xdf, 0xa0, 0x96, 0x24, 0x15, 0x32, 0x92, 0x75, 0x4a, 0xba, 0x0e,
	0x7d, 0x03, 0xc7, 0x3c, 0xe2, 0xd5, 0x33, 0x46, 0x5d, 0xb2, 0x92, 0x20, 0xfe, 0x15, 0x2a, 0xd6,
	0x7a, 0x41, 0x76, 0xef, 0x0a, 0xfa, 0x16, 0x0a, 0xab, 0xb0, 0x82, 0xf5, 0xf7, 0xa4, 0x53, 0xe1,
	0xc3, 0xdd, 0x62, 0x2c, 0xe3, 0x57, 0x9f, 0x58, 0x3c, 0x8d, 0xbf, 0x87, 0xaa, 0xc4, 0x2c, 0x44,
	0x9f, 0x41, 0x31, 0xa0, 0x0e, 0x5d, 0x07, 0x8c, 0xb7, 0x64, 0x89, 0x08, 0x5f, 0x41, 0xb5, 0xb7,
	0x72, 0x5e, 0x8c, 0xf5, 0x72, 0xba, 0xe9, 0x5b, 0x1d, 0x20, 0x7c, 0x6c, 0x42, 0x88, 0x84, 0xe0,
	0x1f, 0x00, 0xc9, 0x45, 0x9b, 0x47, 0xb8, 0x0c, 0x11, 0xa3, 0x21, 0x22, 0xdc, 0x86, 0x63, 0x9d,
	0x52, 0xe7, 0xf1, 0x79, 0x57, 0xfa, 0x6b, 0x38, 0x0f, 0xe9, 0x5d, 0xce, 0x9f, 0xe8, 0xd0, 0xc7,
	0x4a, 0x2f, 0xa1, 0x26, 0x97, 0xca, 0xa3, 0xc3, 0xd5, 0xf0, 0xd1, 0x29, 0x58, 0x51, 0x18, 0xce,
	0xa7, 0x4d, 0x3d, 0xff, 0x5d, 0x2b, 0xfb, 0x37, 0xb3, 0x32, 0xa9, 0x68, 0xa7, 0xa5, 0xdd, 0xbc,
	0x82, 0x9c, 0xfc, 0x0a, 0xb8, 0x81, 0x79, 0xbe, 0xff, 0x0e, 0x03, 0x63, 0xa7, 0x75, 0x8a, 0x7f,
	0x82, 0x33, 0xdd, 0x75, 0xbd, 0xb5, 0xfb, 0x48, 0x1e, 0xe6, 0xae, 0xcb, 0x6e, 0xbc, 0xcb, 0x05,
	0x4c, 0x38, 0xdf, 0xaa, 0xdb, 0xf5, 0x0e, 0x7c, 0x8c, 0xc5, 0xbe, 0x88, 0xe8, 0xbb, 0xff, 0x14,
	0x28, 0xc7, 0x83, 0x88, 0x4e, 0x00, 0x0c, 0xd3, 0xe8, 0x4f, 0x7e, 0xd6, 0xc7, 0xdd, 0xdb, 0xca,
	0x1e, 0xaa, 0x41, 0xc5, 0x1e, 0x1a, 0x83, 0x51, 0x7f, 0x62, 0x99, 0x0f, 0x02, 0x55, 0x24, 0xb4,
	0x6b, 0x8e, 0x04, 0x9a, 0x43, 0x17, 0xf0, 0xb9, 0x40, 0x7b, 0x43, 0x7d, 0x60, 0x1a, 0x7a, 0x94,
	0xca, 0x23, 0x04, 0x27, 0xe3, 0x07, 0x33, 0xe4, 0xb0, 0x05, 0xb6, 0x1f, 0x61, 0x5d, 0x73, 0x14,
	0x61, 0x05, 0x74, 0x06, 0x28, 0xc4, 0x52, 0xf5, 0xc5, 0x50, 0xd6, 0xcd, 0xfd, 0x68, 0x34, 0xb9,
	0x35, 0xef, 0xed, 0x7e, 0xe5, 0xa0, 0xf3, 0x6f, 0x11, 0xf6, 0x07, 0xe1, 0xc6, 0x0e, 0xe1, 0x88,
	0x7d, 0x07, 0x0c, 0xf2, 0xc2, 0x62, 0x4d, 0xac, 0x56, 0xc6, 0xe7, 0x4a, 0xfb, 0x22, 0x33, 0xc7,
	0x9b, 0x87, 0xf7, 0x50, 0x0f, 0x0e, 0x07, 0x84, 0x0e, 0x84, 0x19, 0x23, 0x55, 0x9c, 0xde, 0xfa,
	0x28, 0x68, 0x17, 0x19, 0x99, 0x98, 0x45, 0x07, 0xd0, 0x67, 0x33, 0x9d, 0x1b, 0x0f, 0x3a, 0x17,
	0x47, 0xd3, 0xb6, 0xae, 0xa9, 0xdb, 0x89, 0x98, 0xe2, 0x06, 0x0e, 0xc3, 0xc5, 0x11, 0x3e, 0x8a,
	0xa2, 0xc7, 0x6d, 0x7b, 0xb1, 0xa6, 0x65, 0xa5, 0x62, 0x9e, 0x21, 0x1c, 0xc9, 0x2e, 0x18, 0xf7,
	0x26, 0xc3, 0x6f, 0xe3, 0xde, 0x64, 0xd9, 0xa6, 0xb8, 0x95, 0xef, 0x2f, 0x5e, 0xd9, 0xa0, 0xc4,
	0xb7, 0x4a, 0xbb, 0x60, 0x7c, 0xab, 0x2d, 0x13, 0xe3, 0xed, 0x0d, 0xf7, 0x5b, 0xe7, 0xfb, 0x1d,
	0xb7, 0x77, 0xcb, 0xc2, 0xe2, 0xf6, 0x6e, 0xfb, 0x14, 0x63, 0x11, 0x8e, 0x34, 0xf6, 0xc2, 0x7c,
	0x80, 0x6a, 0x51, 0x23, 0x65, 0x9f, 0x7a, 0x93, 0xe3, 0x52, 0x41, 0xbf, 0x40, 0x25, 0x6d, 0x53,
	0xa8, 0x2e, 0x95, 0x64, 0xf8, 0x57, 0xdc, 0xa1, 0x2c, 0x93, 0xc2, 0x7b, 0x68, 0x0c, 0x9f, 0xa5,
	0xf6, 0x12, 0x7d, 0x15, 0x49, 0xcb, 0xdc, 0x73, 0xad, 0xfe, 0xa1, 0xb4, 0x24, 0xb4, 0x0b, 0xa5,
	0xd0, 0xad, 0xd8, 0x68, 0x5f, 0xc4, 0xe3, 0x9b, 0xf6, 0x3c, 0x4d, 0xcb, 0x4a, 0x45, 0x34, 0xd3,
	0x22, 0x4b, 0x5e, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x86, 0xd8, 0xc3, 0x68, 0xfb, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GameClient is the client API for Game service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameClient interface {
	StartNewGame(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	GetGameLink(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	AddAPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error)
	ListPlayers(ctx context.Context, in *PlayersListRequest, opts ...grpc.CallOption) (*PlayersListResponse, error)
	EnablePlayer(ctx context.Context, in *EnablePlayerRequest, opts ...grpc.CallOption) (*EnablePlayerResponse, error)
	ApplyRules(ctx context.Context, in *RulesListRequest, opts ...grpc.CallOption) (*RulesListResponse, error)
	DrawANumber(ctx context.Context, in *DrawNumberRequest, opts ...grpc.CallOption) (*DrawNumberResponse, error)
	AttachToDraws(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (Game_AttachToDrawsClient, error)
	DrawnNumbersList(ctx context.Context, in *DrawnNumbersListRequest, opts ...grpc.CallOption) (*DrawnNumbersResponse, error)
	AnnounceWinners(ctx context.Context, in *AnnounceWinnersRequest, opts ...grpc.CallOption) (Game_AnnounceWinnersClient, error)
	StopGame(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
}

type gameClient struct {
	cc *grpc.ClientConn
}

func NewGameClient(cc *grpc.ClientConn) GameClient {
	return &gameClient{cc}
}

func (c *gameClient) StartNewGame(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/StartNewGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) GetGameLink(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/GetGameLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) AddAPlayer(ctx context.Context, in *AddPlayerRequest, opts ...grpc.CallOption) (*AddPlayerResponse, error) {
	out := new(AddPlayerResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/AddAPlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) ListPlayers(ctx context.Context, in *PlayersListRequest, opts ...grpc.CallOption) (*PlayersListResponse, error) {
	out := new(PlayersListResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/ListPlayers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) EnablePlayer(ctx context.Context, in *EnablePlayerRequest, opts ...grpc.CallOption) (*EnablePlayerResponse, error) {
	out := new(EnablePlayerResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/EnablePlayer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) ApplyRules(ctx context.Context, in *RulesListRequest, opts ...grpc.CallOption) (*RulesListResponse, error) {
	out := new(RulesListResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/ApplyRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) DrawANumber(ctx context.Context, in *DrawNumberRequest, opts ...grpc.CallOption) (*DrawNumberResponse, error) {
	out := new(DrawNumberResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/DrawANumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) AttachToDraws(ctx context.Context, in *AttachRequest, opts ...grpc.CallOption) (Game_AttachToDrawsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[0], "/proto.Game/AttachToDraws", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameAttachToDrawsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_AttachToDrawsClient interface {
	Recv() (*DrawNumberResponse, error)
	grpc.ClientStream
}

type gameAttachToDrawsClient struct {
	grpc.ClientStream
}

func (x *gameAttachToDrawsClient) Recv() (*DrawNumberResponse, error) {
	m := new(DrawNumberResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) DrawnNumbersList(ctx context.Context, in *DrawnNumbersListRequest, opts ...grpc.CallOption) (*DrawnNumbersResponse, error) {
	out := new(DrawnNumbersResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/DrawnNumbersList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameClient) AnnounceWinners(ctx context.Context, in *AnnounceWinnersRequest, opts ...grpc.CallOption) (Game_AnnounceWinnersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Game_serviceDesc.Streams[1], "/proto.Game/AnnounceWinners", opts...)
	if err != nil {
		return nil, err
	}
	x := &gameAnnounceWinnersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Game_AnnounceWinnersClient interface {
	Recv() (*AnnounceWinnersResponse, error)
	grpc.ClientStream
}

type gameAnnounceWinnersClient struct {
	grpc.ClientStream
}

func (x *gameAnnounceWinnersClient) Recv() (*AnnounceWinnersResponse, error) {
	m := new(AnnounceWinnersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *gameClient) StopGame(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, "/proto.Game/StopGame", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServer is the server API for Game service.
type GameServer interface {
	StartNewGame(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	GetGameLink(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	AddAPlayer(context.Context, *AddPlayerRequest) (*AddPlayerResponse, error)
	ListPlayers(context.Context, *PlayersListRequest) (*PlayersListResponse, error)
	EnablePlayer(context.Context, *EnablePlayerRequest) (*EnablePlayerResponse, error)
	ApplyRules(context.Context, *RulesListRequest) (*RulesListResponse, error)
	DrawANumber(context.Context, *DrawNumberRequest) (*DrawNumberResponse, error)
	AttachToDraws(*AttachRequest, Game_AttachToDrawsServer) error
	DrawnNumbersList(context.Context, *DrawnNumbersListRequest) (*DrawnNumbersResponse, error)
	AnnounceWinners(*AnnounceWinnersRequest, Game_AnnounceWinnersServer) error
	StopGame(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
}

func RegisterGameServer(s *grpc.Server, srv GameServer) {
	s.RegisterService(&_Game_serviceDesc, srv)
}

func _Game_StartNewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StartNewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/StartNewGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StartNewGame(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_GetGameLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).GetGameLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/GetGameLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).GetGameLink(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_AddAPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).AddAPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/AddAPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).AddAPlayer(ctx, req.(*AddPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_ListPlayers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).ListPlayers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/ListPlayers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).ListPlayers(ctx, req.(*PlayersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_EnablePlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnablePlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).EnablePlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/EnablePlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).EnablePlayer(ctx, req.(*EnablePlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_ApplyRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RulesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).ApplyRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/ApplyRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).ApplyRules(ctx, req.(*RulesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_DrawANumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawNumberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).DrawANumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/DrawANumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).DrawANumber(ctx, req.(*DrawNumberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_AttachToDraws_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AttachRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).AttachToDraws(m, &gameAttachToDrawsServer{stream})
}

type Game_AttachToDrawsServer interface {
	Send(*DrawNumberResponse) error
	grpc.ServerStream
}

type gameAttachToDrawsServer struct {
	grpc.ServerStream
}

func (x *gameAttachToDrawsServer) Send(m *DrawNumberResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Game_DrawnNumbersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawnNumbersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).DrawnNumbersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/DrawnNumbersList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).DrawnNumbersList(ctx, req.(*DrawnNumbersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Game_AnnounceWinners_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AnnounceWinnersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GameServer).AnnounceWinners(m, &gameAnnounceWinnersServer{stream})
}

type Game_AnnounceWinnersServer interface {
	Send(*AnnounceWinnersResponse) error
	grpc.ServerStream
}

type gameAnnounceWinnersServer struct {
	grpc.ServerStream
}

func (x *gameAnnounceWinnersServer) Send(m *AnnounceWinnersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Game_StopGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServer).StopGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Game/StopGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServer).StopGame(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Game_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Game",
	HandlerType: (*GameServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartNewGame",
			Handler:    _Game_StartNewGame_Handler,
		},
		{
			MethodName: "GetGameLink",
			Handler:    _Game_GetGameLink_Handler,
		},
		{
			MethodName: "AddAPlayer",
			Handler:    _Game_AddAPlayer_Handler,
		},
		{
			MethodName: "ListPlayers",
			Handler:    _Game_ListPlayers_Handler,
		},
		{
			MethodName: "EnablePlayer",
			Handler:    _Game_EnablePlayer_Handler,
		},
		{
			MethodName: "ApplyRules",
			Handler:    _Game_ApplyRules_Handler,
		},
		{
			MethodName: "DrawANumber",
			Handler:    _Game_DrawANumber_Handler,
		},
		{
			MethodName: "DrawnNumbersList",
			Handler:    _Game_DrawnNumbersList_Handler,
		},
		{
			MethodName: "StopGame",
			Handler:    _Game_StopGame_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AttachToDraws",
			Handler:       _Game_AttachToDraws_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "AnnounceWinners",
			Handler:       _Game_AnnounceWinners_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "game.proto",
}
